package com.taktak.service;

import com.taktak.model.*; import com.taktak.repository.*; import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.math.*; import java.security.SecureRandom; import java.time.LocalDateTime; import java.util.*;

@Service @RequiredArgsConstructor
public class RewardService {
 private final CafeRepository cafes; private final OrderRepository orders; private final RewardCampaignRepository campaigns; private final RewardOptionRepository options; private final CustomerFeedbackRepository feedbacks; private final CouponRepository coupons; private final CouponEmailService email; private final SecureRandom random=new SecureRandom();
 @Transactional(readOnly=true) public CampaignView getCampaign(String slug){RewardCampaign c=campaigns.findByCafeId(cafe(slug).getId()).orElse(null);return c==null?new CampaignView(false,null,30,30,BigDecimal.ZERO,List.of()):view(c);}
 @Transactional public CampaignView saveCampaign(String slug,CampaignRequest r){
  Cafe cafe=cafe(slug); if(r.couponValidDays()==null||r.couponValidDays()<1||r.couponValidDays()>365)bad("Validité invalide");if(r.participationCooldownDays()==null||r.participationCooldownDays()<1||r.participationCooldownDays()>365)bad("Délai de participation invalide"); List<OptionRequest> list=r.options()==null?List.of():r.options();
  BigDecimal sum=list.stream().filter(o->Boolean.TRUE.equals(o.enabled())).map(OptionRequest::probabilityPercent).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add); if(r.enabled()&&(list.isEmpty()||sum.compareTo(new BigDecimal("100"))!=0))bad("Les probabilités actives doivent totaliser 100%");
  for(OptionRequest o:list)if(o.label()==null||o.label().isBlank()||o.discountPercent()==null||o.discountPercent().signum()<0||o.discountPercent().compareTo(new BigDecimal("100"))>0||o.probabilityPercent()==null||o.probabilityPercent().signum()<0)bad("Option de gain invalide");
  RewardCampaign c=campaigns.findByCafeId(cafe.getId()).orElseGet(()->RewardCampaign.builder().cafeId(cafe.getId()).build());c.setEnabled(r.enabled());c.setGoogleReviewUrl(r.googleReviewUrl());c.setCouponValidDays(r.couponValidDays());c.setParticipationCooldownDays(r.participationCooldownDays());c.setMinimumOrderAmount(r.minimumOrderAmount()==null?BigDecimal.ZERO:r.minimumOrderAmount());c=campaigns.save(c);options.deleteByCampaignId(c.getId());UUID id=c.getId();list.forEach(o->options.save(RewardOption.builder().campaignId(id).label(o.label()).discountPercent(o.discountPercent()).probabilityPercent(o.probabilityPercent()).enabled(Boolean.TRUE.equals(o.enabled())).build()));return view(c);
 }
 @Transactional public CouponView feedback(String slug,FeedbackRequest r){
  Cafe cafe=cafe(slug);RewardCampaign campaign=campaigns.findByCafeId(cafe.getId()).filter(RewardCampaign::isEnabled).orElseThrow(()->conflict("Campagne inactive"));if(r.rating()==null||r.rating()<1||r.rating()>5)bad("Note invalide");if(r.email()==null||!r.email().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))bad("Email invalide");String normalizedEmail=r.email().trim().toLowerCase();UUID targetOrderId=r.orderId()!=null?r.orderId():UUID.randomUUID();Optional<Coupon> old=coupons.findBySourceOrderId(targetOrderId);if(old.isPresent())return coupon(old.get(),campaign.getGoogleReviewUrl());if(feedbacks.existsByOrderId(targetOrderId))throw conflict("Avis déjà enregistré");if(feedbacks.existsByCafeIdAndCustomerEmailIgnoreCaseAndCreatedAtAfter(cafe.getId(),normalizedEmail,LocalDateTime.now().minusDays(campaign.getParticipationCooldownDays())))throw conflict("Cet email a déjà participé récemment");
  feedbacks.save(CustomerFeedback.builder().cafeId(cafe.getId()).orderId(targetOrderId).rating(r.rating()).comment(r.comment()).customerEmail(r.email().trim().toLowerCase()).build());List<RewardOption> active=options.findByCampaignIdAndEnabledTrue(campaign.getId());if(active.isEmpty())throw conflict("Aucun gain configuré");RewardOption won=draw(active);Coupon c=coupons.save(Coupon.builder().code(code()).cafeId(cafe.getId()).sourceOrderId(targetOrderId).customerEmail(r.email().trim().toLowerCase()).rewardLabel(won.getLabel()).discountPercent(won.getDiscountPercent()).minimumOrderAmount(campaign.getMinimumOrderAmount()).status(CouponStatus.ACTIVE).expiresAt(LocalDateTime.now().plusDays(campaign.getCouponValidDays())).build());email.send(c,cafe.getName());return coupon(c,campaign.getGoogleReviewUrl());
 }
 @Transactional public ValidationView validate(String slug,String code,BigDecimal amount){Coupon c=requireUsable(cafe(slug).getId(),code,amount);BigDecimal d=amount.multiply(c.getDiscountPercent()).divide(new BigDecimal("100"),3,RoundingMode.HALF_UP);return new ValidationView(true,c.getCode(),c.getRewardLabel(),c.getDiscountPercent(),d,amount.subtract(d),c.getExpiresAt());}
 @Transactional public ManualCouponView createManualCoupon(String slug,ManualCouponRequest r){
  Cafe cafe=cafe(slug);if(r.email()==null||!r.email().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"))bad("Email invalide");if(r.discountPercent()==null||r.discountPercent().signum()<=0||r.discountPercent().compareTo(new BigDecimal("100"))>0)bad("Réduction invalide");if(r.validDays()==null||r.validDays()<1||r.validDays()>365)bad("Validité invalide");BigDecimal minimum=r.minimumOrderAmount()==null?BigDecimal.ZERO:r.minimumOrderAmount();if(minimum.signum()<0)bad("Montant minimum invalide");String label=r.label()==null||r.label().isBlank()?r.discountPercent().stripTrailingZeros().toPlainString()+"% de réduction":r.label().trim();Coupon c=coupons.save(Coupon.builder().code(code()).cafeId(cafe.getId()).customerEmail(r.email().trim().toLowerCase()).rewardLabel(label).discountPercent(r.discountPercent()).minimumOrderAmount(minimum).status(CouponStatus.ACTIVE).expiresAt(LocalDateTime.now().plusDays(r.validDays())).build());boolean sent=email.send(c,cafe.getName());return new ManualCouponView(c.getId(),c.getCustomerEmail(),c.getRewardLabel(),c.getDiscountPercent(),c.getExpiresAt(),sent);
 }
 @Transactional public Coupon requireUsable(UUID cafeId,String code,BigDecimal amount){if(code==null||code.isBlank())bad("Code obligatoire");Coupon c=coupons.findByCodeForUpdate(code.trim()).orElseThrow(()->notFound("Coupon introuvable"));if(!c.getCafeId().equals(cafeId))bad("Coupon invalide");if(c.getStatus()==CouponStatus.ACTIVE&&c.getExpiresAt().isBefore(LocalDateTime.now())){c.setStatus(CouponStatus.EXPIRED);coupons.save(c);}if(c.getStatus()!=CouponStatus.ACTIVE)throw conflict("Coupon indisponible");if(amount==null||amount.compareTo(c.getMinimumOrderAmount())<0)throw conflict("Montant minimum non atteint");return c;}
 private RewardOption draw(List<RewardOption> list){double n=random.nextDouble()*list.stream().mapToDouble(o->o.getProbabilityPercent().doubleValue()).sum();for(RewardOption o:list){n-=o.getProbabilityPercent().doubleValue();if(n<0)return o;}return list.get(list.size()-1);} private String code(){String c;do{c="TAK-"+UUID.randomUUID().toString().replace("-","").substring(0,10).toUpperCase();}while(coupons.findByCodeIgnoreCase(c).isPresent());return c;}
 private Cafe cafe(String s){return cafes.findBySlug(s).orElseThrow(()->notFound("Café introuvable"));}private CampaignView view(RewardCampaign c){return new CampaignView(c.isEnabled(),c.getGoogleReviewUrl(),c.getCouponValidDays(),c.getParticipationCooldownDays(),c.getMinimumOrderAmount(),options.findByCampaignIdOrderByDiscountPercentAsc(c.getId()).stream().map(o->new OptionView(o.getId(),o.getLabel(),o.getDiscountPercent(),o.getProbabilityPercent(),o.isEnabled())).toList());} private CouponView coupon(Coupon c,String url){return new CouponView(c.getCode(),c.getRewardLabel(),c.getDiscountPercent(),c.getExpiresAt(),url);}private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private ResponseStatusException notFound(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 public record OptionRequest(String label,BigDecimal discountPercent,BigDecimal probabilityPercent,Boolean enabled){} public record CampaignRequest(boolean enabled,String googleReviewUrl,Integer couponValidDays,Integer participationCooldownDays,BigDecimal minimumOrderAmount,List<OptionRequest> options){} public record OptionView(UUID id,String label,BigDecimal discountPercent,BigDecimal probabilityPercent,boolean enabled){} public record CampaignView(boolean enabled,String googleReviewUrl,Integer couponValidDays,Integer participationCooldownDays,BigDecimal minimumOrderAmount,List<OptionView> options){} public record FeedbackRequest(UUID orderId,Integer rating,String comment,String email){} public record CouponView(String code,String rewardLabel,BigDecimal discountPercent,LocalDateTime expiresAt,String googleReviewUrl){} public record ManualCouponRequest(String email,BigDecimal discountPercent,Integer validDays,BigDecimal minimumOrderAmount,String label){} public record ManualCouponView(UUID id,String email,String rewardLabel,BigDecimal discountPercent,LocalDateTime expiresAt,boolean emailSent){} public record ValidationView(boolean valid,String code,String rewardLabel,BigDecimal discountPercent,BigDecimal discountAmount,BigDecimal finalAmount,LocalDateTime expiresAt){}
}
